### ISSUE TITLE
is project dead ?

### ISSUE THREAD

**Issue by extremety1989** [maierfelix/glmw#4]

**Comment by maierfelix** [comment]
I will likely continue as soon as chrome's wasm implementation gets as speedy as firefox. Pull requests are welcome though, it's straightforward to convert gl-matrix code to C. The language bridges are already done, only modules like ``quat`` are left

**Comment by extremety1989** [comment]
aa okey, i want try  to do neural network trying to use your librairy, is it possible ?
to do matrix of N x N ?  like 4096 rows time 4096 cols matrix multiplication

**Comment by maierfelix** [comment]
I recommend you to checkout [node-vulkan](https://github.com/maierfelix/node-vulkan) which is a low-level API to [Vulkan](https://en.wikipedia.org/wiki/Vulkan_(API)). Vulkan itself is built with compute shaders in focus, so if you want to do parallel computations (on the GPU) very fast, this might be fitting for you.

Edit: There are good examples out there how to write a Vulkan compute shader in a few hundred lines. You can easily port the C/C++ code from there, since `node-vulkan` is a 1:1 API to Vulkan's C99 API.

**Comment by extremety1989** [comment]
glsl programming is new to me too complicated))
